# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lunaris.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x0elunaris.worker\x1a\x0c\x63ommon.proto\"\x8f\x02\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12\x13\n\x0bwasm_module\x18\x02 \x01(\x0c\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x12\r\n\x05\x65ntry\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\r\x12)\n\x08wasi_env\x18\x06 \x01(\x0b\x32\x17.lunaris.common.WasiEnv\x12\x39\n\x10\x65xecution_limits\x18\x07 \x01(\x0b\x32\x1f.lunaris.common.ExecutionLimits\x12\x0f\n\x07\x61ttempt\x18\x08 \x01(\r\x12;\n\x11host_capabilities\x18\t \x01(\x0b\x32 .lunaris.common.HostCapabilities\"A\n\x0cTaskAccepted\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x03 \x01(\r\"\xa4\x01\n\x0e\x43ontrolCommand\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.lunaris.worker.ControlCommand.CommandType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"J\n\x0b\x43ommandType\x12\r\n\tHEARTBEAT\x10\x00\x12\x0c\n\x08SHUTDOWN\x10\x01\x12\x0f\n\x0b\x43\x41NCEL_TASK\x10\x02\x12\r\n\tSET_DRAIN\x10\x03\"\x8a\x01\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x34\n\x06status\x18\x02 \x01(\x0e\x32$.lunaris.worker.NodeStatus.NodeState\x12\x14\n\x0c\x63urrent_task\x18\x03 \x01(\r\"\x1f\n\tNodeState\x12\x08\n\x04IDLE\x10\x00\x12\x08\n\x04\x42USY\x10\x01\"\x8c\x02\n\x10NodeRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rch\x18\x02 \x01(\t\x12\x17\n\x0fmax_concurrency\x18\x03 \x01(\r\x12\x13\n\x0bmemory_size\x18\x04 \x01(\x04\x12\r\n\x05token\x18\x05 \x01(\t\x12?\n\x15provided_capabilities\x18\x06 \x01(\x0b\x32 .lunaris.common.HostCapabilities\x12\x39\n\x04type\x18\x07 \x01(\x0e\x32+.lunaris.worker.NodeRegistration.WorkerType\"#\n\nWorkerType\x12\x0c\n\x08STANDARD\x10\x00\x12\x07\n\x03MCU\x10\x01\"(\n\x15NodeRegistrationReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"!\n\x0eUnregisterNode\x12\x0f\n\x07node_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=47
  _globals['_TASK']._serialized_end=318
  _globals['_TASKACCEPTED']._serialized_start=320
  _globals['_TASKACCEPTED']._serialized_end=385
  _globals['_CONTROLCOMMAND']._serialized_start=388
  _globals['_CONTROLCOMMAND']._serialized_end=552
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_start=478
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_end=552
  _globals['_NODESTATUS']._serialized_start=555
  _globals['_NODESTATUS']._serialized_end=693
  _globals['_NODESTATUS_NODESTATE']._serialized_start=662
  _globals['_NODESTATUS_NODESTATE']._serialized_end=693
  _globals['_NODEREGISTRATION']._serialized_start=696
  _globals['_NODEREGISTRATION']._serialized_end=964
  _globals['_NODEREGISTRATION_WORKERTYPE']._serialized_start=929
  _globals['_NODEREGISTRATION_WORKERTYPE']._serialized_end=964
  _globals['_NODEREGISTRATIONREPLY']._serialized_start=966
  _globals['_NODEREGISTRATIONREPLY']._serialized_end=1006
  _globals['_UNREGISTERNODE']._serialized_start=1008
  _globals['_UNREGISTERNODE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
