FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml uv.lock README.md /app/
COPY lunaris /app/lunaris
COPY proto /app/proto

RUN pip install --no-cache-dir uv \
    && uv pip install --system .

CMD ["python", "-m", "lunaris", "worker"]

