# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/worker.proto\x12\x0elunaris.worker\x1a\x12proto/common.proto\"\xe9\x01\n\x08\x45nvelope\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.lunaris.worker.Envelope.MessageType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x97\x01\n\x0bMessageType\x12\x08\n\x04TASK\x10\x00\x12\x0f\n\x0bTASK_RESULT\x10\x01\x12\x13\n\x0f\x43ONTROL_COMMAND\x10\x02\x12\x0f\n\x0bNODE_STATUS\x10\x03\x12\x15\n\x11NODE_REGISTRATION\x10\x04\x12\x1b\n\x17NODE_REGISTRATION_REPLY\x10\x05\x12\x13\n\x0fUNREGISTER_NODE\x10\x06\"v\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x12/\n\x0blua_version\x18\x04 \x01(\x0e\x32\x1a.lunaris.common.LuaVersion\x12\x10\n\x08priority\x18\x05 \x01(\x05\"\x84\x01\n\x0e\x43ontrolCommand\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.lunaris.worker.ControlCommand.CommandType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"*\n\x0b\x43ommandType\x12\r\n\tHEARTBEAT\x10\x00\x12\x0c\n\x08SHUTDOWN\x10\x01\"\x8a\x01\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x34\n\x06status\x18\x02 \x01(\x0e\x32$.lunaris.worker.NodeStatus.NodeState\x12\x14\n\x0c\x63urrent_task\x18\x03 \x01(\x05\"\x1f\n\tNodeState\x12\x08\n\x04IDLE\x10\x00\x12\x08\n\x04\x42USY\x10\x01\"y\n\x10NodeRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02os\x18\x02 \x01(\t\x12\x0c\n\x04\x61rch\x18\x03 \x01(\t\x12\x17\n\x0fmax_concurrency\x18\x04 \x01(\x05\x12\x0f\n\x07num_cpu\x18\x06 \x01(\x05\x12\x13\n\x0bmemory_size\x18\x07 \x01(\x05\"(\n\x15NodeRegistrationReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"!\n\x0eUnregisterNode\x12\x0f\n\x07node_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=59
  _globals['_ENVELOPE']._serialized_end=292
  _globals['_ENVELOPE_MESSAGETYPE']._serialized_start=141
  _globals['_ENVELOPE_MESSAGETYPE']._serialized_end=292
  _globals['_TASK']._serialized_start=294
  _globals['_TASK']._serialized_end=412
  _globals['_CONTROLCOMMAND']._serialized_start=415
  _globals['_CONTROLCOMMAND']._serialized_end=547
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_start=505
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_end=547
  _globals['_NODESTATUS']._serialized_start=550
  _globals['_NODESTATUS']._serialized_end=688
  _globals['_NODESTATUS_NODESTATE']._serialized_start=657
  _globals['_NODESTATUS_NODESTATE']._serialized_end=688
  _globals['_NODEREGISTRATION']._serialized_start=690
  _globals['_NODEREGISTRATION']._serialized_end=811
  _globals['_NODEREGISTRATIONREPLY']._serialized_start=813
  _globals['_NODEREGISTRATIONREPLY']._serialized_end=853
  _globals['_UNREGISTERNODE']._serialized_start=855
  _globals['_UNREGISTERNODE']._serialized_end=888
# @@protoc_insertion_point(module_scope)
